apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jenkins-dev-01
  namespace: jenkins-dev-01
spec:
  storageClassName: pv-jenkins-dev-01
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/jenkins-volume/
