InstallPlugins:
    - ansicolor:0.5.2
    - authentication-tokens:1.3
    - blueocean-autofavorite:1.0.0
    - cloudbees-bitbucket-branch-source:2.2.3
    - blueocean-bitbucket-pipeline:1.2.4
    - bitbucket:1.1.5
    - bitbucket-pullrequest-builder:1.4.26
    - blueocean:1.2.4
    - blueocean-pipeline-editor:1.2.4
    - branch-api:2.0.11
    - blueocean-commons:1.2.4
    - blueocean-config:1.2.4
    - credentials-binding:1.13
    - credentials:2.1.16
    - blueocean-dashboard:1.2.4
    - display-url-api:2.0
    - blueocean-display-url:2.1.0
    - docker-commons:1.8
    - docker-workflow:1.13
    - durable-task:1.14
    - blueocean-events:1.2.4
    - favorite:2.3.0
    - cloudbees-folder:6.1.2
    - git-server:1.7
    - blueocean-git-pipeline:1.2.4
    - git-client:2.5.0
    - git:3.5.1
    - github-api:1.86
    - github-branch-source:2.2.3
    - blueocean-github-pipeline:1.2.4
    - github:1.28.0
    - htmlpublisher:1.14
    - icon-shim:2.0.3
    - blueocean-jira:1.2.4
    - jira:2.4.2
    - junit:1.21
    - blueocean-jwt:1.2.4
    - jackson2-api:2.7.3
    - ace-editor:1.1
    - handlebars:1.1.1
    - momentjs:1.1.1
    - jquery-detached:1.2.1
    - kubernetes:1.0
    - mailer:1.20
    - matrix-project:1.11
    - mercurial:2.1
    - blueocean-personalization:1.2.4
    - workflow-aggregator:2.5
    - pipeline-graph-analysis:1.5
    - blueocean-pipeline-scm-api:1.2.4
    - blueocean-pipeline-api-impl:1.2.4
    - workflow-api:2.20
    - workflow-basic-steps:2.6
    - pipeline-build-step:2.5.1
    - pipeline-model-declarative-agent:1.1.1
    - pipeline-model-extensions:1.1.9
    - pipeline-github-lib:1.0
    - workflow-cps:2.40
    - pipeline-input-step:2.8
    - workflow-job:2.14.1
    - pipeline-milestone-step:1.3.1
    - pipeline-model-api:1.1.9
    - pipeline-model-definition:1.1.9
    - workflow-multibranch:2.16
    - workflow-durable-task-step:2.15
    - pipeline-rest-api:2.9
    - workflow-scm-step:2.6
    - workflow-cps-global-lib:2.9
    - pipeline-stage-step:2.2
    - pipeline-stage-tags-metadata:1.1.9
    - pipeline-stage-view:2.9
    - workflow-step-api:2.13
    - workflow-support:2.14
    - plain-credentials:1.4
    - pubsub-light:1.12
    - blueocean-rest:1.2.4
    - blueocean-rest-impl:1.2.4
    - scm-api:2.2.2
    - ssh-credentials:1.13
    - script-security:1.34
    - sse-gateway:1.15
    - structs:1.10
    - token-macro:2.3
    - variant:1.1
    - blueocean-web:1.2.4
    - bouncycastle-api:2.16.2
    - blueocean-i18n:1.2.4
