Agent:
  AlwaysPullImage: false
  Component: jenkins-slave
  CustomJenkinsLabels: []
  Enabled: true
  Image: jenkins/jnlp-slave
  ImageTag: 3.27-1
  NodeSelector: {}
  PodRetention: Never
  Privileged: false
  envVars: null
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 256Mi
  volumes: null
Master:
  AdditionalConfig: {}
  AdminUser: admin
  CLI: false
  CSRF:
    DefaultCrumbIssuer:
      Enabled: true
      ProxyCompatability: true
  Component: jenkins-master
  CustomConfigMap: false
  DeploymentLabels: null
  DisabledAgentProtocols:
  - JNLP-connect
  - JNLP2-connect
  ExtraPorts: null
  HealthProbeLivenessFailureThreshold: 12
  HealthProbeReadinessPeriodSeconds: 10
  HealthProbes: true
  HealthProbesLivenessTimeout: 90
  HealthProbesReadinessTimeout: 60
  HostNetworking: false
  Image: jenkins/jenkins
  ImagePullPolicy: Always
  ImageTag: lts
  Ingress:
    Annotations: {}
    ApiVersion: extensions/v1beta1
    TLS: null
  InitScripts: null
  InstallPlugins:
  - ansicolor:0.6.2
  - authentication-tokens:1.3
  - blueocean-autofavorite:1.2.3
  - cloudbees-bitbucket-branch-source:2.4.1
  - blueocean-bitbucket-pipeline:1.10.2
  - bitbucket:1.1.8
  - bitbucket-pullrequest-builder:1.4.29
  - blueocean:1.10.2
  - blueocean-pipeline-editor:1.10.2
  - branch-api:2.1.2
  - blueocean-commons:1.10.2
  - blueocean-config:1.10.2
  - credentials-binding:1.17
  - credentials:2.1.18
  - blueocean-dashboard:1.10.2
  - display-url-api:2.3.0
  - blueocean-display-url:2.2.0
  - docker-commons:1.13
  - docker-workflow:1.17
  - durable-task:1.29
  - blueocean-events:1.10.2
  - favorite:2.3.2
  - cloudbees-folder:6.7
  - git-server:1.7
  - blueocean-git-pipeline:1.10.2
  - git-client:2.7.6
  - git:3.9.3
  - github-api:1.95
  - github-branch-source:2.4.2
  - blueocean-github-pipeline:1.10.2
  - github:1.29.3
  - htmlpublisher:1.18
  - icon-shim:2.0.3
  - blueocean-jira:1.10.2
  - jira:3.0.5
  - junit:1.27
  - blueocean-jwt:1.10.2
  - jackson2-api:2.9.8
  - ace-editor:1.1
  - handlebars:1.1.1
  - momentjs:1.1.1
  - jquery-detached:1.2.1
  - kubernetes:1.14.3
  - mailer:1.23
  - matrix-project:1.13
  - mercurial:2.5
  - blueocean-personalization:1.10.2
  - workflow-aggregator:2.6
  - pipeline-graph-analysis:1.9
  - blueocean-pipeline-scm-api:1.10.2
  - blueocean-pipeline-api-impl:1.10.2
  - workflow-api:2.33
  - workflow-basic-steps:2.14
  - pipeline-build-step:2.7
  - pipeline-model-declarative-agent:1.3.4.1
  - pipeline-model-extensions:1.3.4.1
  - pipeline-github-lib:1.0
  - workflow-cps:2.63
  - pipeline-input-step:2.9
  - workflow-job:2.31
  - pipeline-milestone-step:1.3.1
  - pipeline-model-api:1.3.4.1
  - pipeline-model-definition:1.1.9
  - workflow-multibranch:2.20
  - workflow-durable-task-step:2.29
  - pipeline-rest-api:2.10
  - workflow-scm-step:2.7
  - workflow-cps-global-lib:2.13
  - pipeline-stage-step:2.3
  - pipeline-stage-tags-metadata:1.3.4.1
  - pipeline-stage-view:2.10
  - workflow-step-api:2.19
  - workflow-support:3.2
  - plain-credentials:1.5
  - pubsub-light:1.12
  - blueocean-rest:1.10.2
  - blueocean-rest-impl:1.10.2
  - scm-api:2.3.0
  - ssh-credentials:1.14
  - script-security:1.51
  - sse-gateway:1.17
  - structs:1.17
  - token-macro:2.6
  - variant:1.1
  - blueocean-web:1.10.2
  - bouncycastle-api:2.17
  - blueocean-i18n:1.10.2
  JCasC:
    ConfigScripts:
      welcome-message: |
        jenkins:
          systemMessage: Welcome to our CI\CD server.  This Jenkins is configured and managed 'as code'.
    PluginVersion: 1.5
    SupportPluginVersion: 1.5
    enabled: false
  LoadBalancerSourceRanges:
  - 0.0.0.0/0
  Name: jenkins-master
  NodeSelector: {}
  NumExecutors: 0
  OverwriteConfig: false
  OwnSshKey: false
  PodAnnotations: {}
  ServiceAnnotations: {}
  ServiceLabels: {}
  ServicePort: 8080
  ServiceType: LoadBalancer
  Sidecar:
    configAutoReload:
      enabled: false
      folder: /var/jenkins_home/casc_configs
      label: jenkins_config
      sshTcpPort: 1044
    image: shadwell/k8s-sidecar:0.0.2
    imagePullPolicy: IfNotPresent
    resources: null
  SidecarContainers: null
  SlaveListenerPort: 50000
  SlaveListenerServiceAnnotations: {}
  SlaveListenerServiceType: ClusterIP
  Tolerations: {}
  UsePodSecurityContext: true
  UseSecurity: true
  resources:
    limits:
      cpu: 2000m
      memory: 4096Mi
    requests:
      cpu: 50m
      memory: 256Mi
NetworkPolicy:
  ApiVersion: networking.k8s.io/v1
  Enabled: false
Persistence:
  AccessMode: ReadWriteOnce
  Annotations: {}
  Enabled: true
  Size: 8Gi
  mounts: null
  volumes: null
backup:
  annotations:
    iam.amazonaws.com/role: jenkins
  destination: s3://nuvo-jenkins-data/backup
  enabled: false
  env:
  - name: AWS_REGION
    value: us-east-1
  extraArgs: []
  image:
    repository: nuvo/kube-tasks
    tag: 0.1.2
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 1
      memory: 1Gi
  schedule: 0 2 * * *
rbac:
  install: false
  roleBindingKind: ClusterRoleBinding
  roleKind: ClusterRole
  roleRef: cluster-admin
  serviceAccountName: default
